<script setup>
import {computed,ref,watch,onBeforeUnmount,onMounted,defineAsyncComponent} from 'vue'
import {Search,Orbit,Route,GitCompareArrows,Compass,Map,Library,ArrowUpRight,ArrowRight,RotateCcw,Maximize2,Minimize2,SlidersHorizontal,Play,Pause,Download,ChevronRight,X,BookOpen,Check,Command,PanelRightClose,PanelRightOpen} from 'lucide-vue-next'
import {useUniverse} from './store'
import {levels,typeNames,typeColors,relationNames} from './lib/graph'
import KnowledgeCard from './components/KnowledgeCard.vue'
import ResourceViewer from './components/ResourceViewer.vue'
const UniverseScene=defineAsyncComponent(()=>import('./components/UniverseScene.vue'))
const s=useUniverse(),searchInput=ref(),searchOpen=ref(false),cardVisible=ref(true),resourceQuery=ref(''),caseDomain=ref('all'),directoryQuery=ref(''),tourTimer=ref(null)
const tabs=[{id:'universe',label:'知识宇宙',icon:Orbit},{id:'path',label:'学习路径',icon:Route},{id:'compare',label:'方法比较',icon:GitCompareArrows},{id:'problems',label:'问题导航',icon:Compass},{id:'cases',label:'案例地图',icon:Map},{id:'resources',label:'课程资源',icon:Library}]
const modeLabel=computed(()=>tabs.find(t=>t.id===s.mode)?.label||'知识目录')
const resourceList=computed(()=>s.resources.filter(r=>(r.title+r.kind).toLowerCase().includes(resourceQuery.value.toLowerCase())))
const caseList=computed(()=>s.cases.filter(c=>caseDomain.value==='all'||c.domain===caseDomain.value))
const directory=computed(()=>s.filtered.filter(n=>(n.name+n.id).toLowerCase().includes(directoryQuery.value.toLowerCase())))
const selectedResources=computed(()=>s.resources.filter(r=>s.selected.resource_ids.includes(r.id)))
const displayCount=computed(()=>s.filtered.length)
function setMode(mode){s.setMode(mode);if(mode==='compare')s.focus(s.comparison.method_ids[0]);if(mode==='path')s.focus(s.pathTarget);if(mode==='cases')s.focus(s.caseItem.node_id);if(mode==='problems')s.focus(s.problem.method_ids[0])}
function stopTour(){clearTimeout(tourTimer.value);tourTimer.value=null;s.tourIndex=-1}
function tourStep(){if(s.tourIndex>=s.path.length){stopTour();return}s.focus(s.path[s.tourIndex]);tourTimer.value=setTimeout(()=>{s.tourIndex++;tourStep()},2600)}
function toggleTour(){if(tourTimer.value){stopTour();return}s.tourIndex=0;tourStep()}
function exportPath(){const text=['# '+s.byId[s.pathTarget].name+' · 学习路径','按课程先修关系计算，包含所有前置分支；以下为一种拓扑学习顺序。','',...s.path.map((id,i)=>`${i+1}. ${s.byId[id].name}\n   ${s.byId[id].sources.map(x=>s.resources.find(r=>r.id===x.resource_id).source_path+' '+x.locator).join('; ')}`)].join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='学习路径.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function keyboard(e){if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();searchInput.value?.focus()}if(e.key==='Escape'){searchOpen.value=false;stopTour()}}
watch(()=>[s.mode,s.pathTarget,s.pathDirection],stopTour)
watch(()=>s.comparisonId,()=>s.focus(s.comparison.method_ids[0]));watch(()=>s.caseId,()=>s.focus(s.caseItem.node_id));watch(()=>s.problemId,()=>s.focus(s.problem.method_ids[0]))
onMounted(()=>window.addEventListener('keydown',keyboard));onBeforeUnmount(()=>{stopTour();window.removeEventListener('keydown',keyboard)})
const relationText=computed(()=>s.mode==='path'?'路径保留所有先修分支 · 编号表示一种可行学习顺序':s.mode==='compare'?'高亮方法组成与共同基础 · 连线可在知识卡中核对':s.mode==='cases'?'案例按任务领域组织 · 所有案例对应原课程材料':'X–Y 表示知识领域 · Z 表示认知高度')
</script>
<template>
 <div class="app-shell" :class="{'presentation':s.presentation,'card-hidden':!cardVisible}">
  <header class="app-header"><a href="#" class="brand" @click.prevent="setMode('universe');s.reset()"><span class="brand-mark"><Orbit :size="29"/></span><div><strong>多元统计分析<span class="brand-divider"> / </span><span class="brand-sub">三维知识空间</span></strong><small>MULTIVARIATE STATISTICS · KNOWLEDGE UNIVERSE</small></div></a>
   <div class="search-wrap"><Search :size="17"/><input ref="searchInput" aria-label="搜索知识节点" placeholder="搜索知识、方法或 Python…" v-model="s.query" @focus="searchOpen=true" @keydown.enter="s.searchResults[0]&&(s.focus(s.searchResults[0].id),searchOpen=false)"><kbd>⌘ K</kbd><div v-if="searchOpen&&s.query.trim()" class="search-results"><span class="eyebrow">找到 {{s.searchResults.length}} 个知识单元</span><button v-for="n in s.searchResults.slice(0,12)" :key="n.id" @click="s.focus(n.id);searchOpen=false"><span>{{n.name}}</span><small>L{{n.level}} · {{n.chapter}}</small><ArrowUpRight :size="14"/></button><p v-if="!s.searchResults.length">没有匹配项，可尝试 PCA、因子、回归或章节编号。</p></div></div>
   <span class="version-pill"><span class="status-dot"></span>数字课程 · V2.0</span><button class="icon-button presentation-button" :aria-label="s.presentation?'退出演示模式':'进入演示模式'" @click="s.presentation=!s.presentation"><Minimize2 v-if="s.presentation" :size="19"/><Maximize2 v-else :size="19"/></button>
  </header>
  <nav class="top-nav" aria-label="主导航"><button v-for="tab in tabs" :key="tab.id" :class="{active:s.mode===tab.id}" @click="setMode(tab.id)"><component :is="tab.icon" :size="16"/>{{tab.label}}<span v-if="tab.id==='universe'" class="nav-count">{{s.nodes.length}}</span></button><span class="nav-spacer"></span><button class="directory-toggle" :class="{active:s.mode==='directory'}" @click="setMode('directory')"><BookOpen :size="15"/>知识目录</button></nav>
  <div class="workspace">
   <aside class="left-sidebar"><div class="sidebar-heading"><span class="eyebrow">YOUR KNOWLEDGE ATLAS</span><h2>探索知识星系</h2><p>从一个问题，找到一条学习路线。</p></div>
    <button class="overview-item" :class="{active:s.moduleFilter==='all'}" @click="s.moduleFilter='all';s.reset()"><Orbit :size="18"/><span>课程全景</span><b>{{s.nodes.length}}</b></button>
    <div class="module-list"><button v-for="m in s.modules" :key="m.id" :style="{'--module-color':m.color}" :class="{active:s.moduleFilter===m.id}" @click="s.moduleFilter=s.moduleFilter===m.id?'all':m.id"><span class="module-letter">{{m.id}}</span><span><strong>{{m.name}}</strong><small>{{m.subtitle}}</small></span><b>{{s.nodes.filter(n=>n.module===m.id).length}}</b></button></div>
    <div class="sidebar-section"><h3>核心方法 <span>9 个主题</span></h3><div class="method-shortcuts"><button v-for="id in ['pca','fa','cluster','discriminant','regression','logistic','cca','ca','evaluation']" :key="id" :class="{active:s.selectedId===id}" @click="s.focus(id)">{{s.byId[id].name.replace('分析 PCA',' PCA').replace('分析 FA',' FA').replace('分析 CCA',' CCA').replace('分析 CA',' CA')}}<ArrowUpRight :size="12"/></button></div></div>
    <div class="journey-card"><span class="tiny-icon"><Route :size="18"/></span><h3>从理解到应用</h3><p>以「地区电信业发展」为目标，走过主成分分析的学习路径。</p><button @click="s.makePath('case_pca')">开始探索 <ArrowRight :size="14"/></button></div>
    <footer class="sidebar-footer"><span class="status-dot"></span>来源可追溯 · 12 章课程材料</footer>
   </aside>
   <main class="main-stage">
    <div class="stage-heading"><div><span class="eyebrow">{{s.mode==='universe'?'EXPLORE THE CONNECTIONS':modeLabel==='学习路径'?'BUILD YOUR LEARNING JOURNEY':'DISCOVER WITH PURPOSE'}}</span><h1>{{s.mode==='universe'?'让知识连接，让学习发生。':modeLabel}}</h1><p>{{relationText}}</p></div><div class="stage-tools"><button class="icon-button" title="返回全景" aria-label="返回全景" @click="s.reset()"><RotateCcw :size="17"/></button><button class="icon-button" :aria-label="cardVisible?'收起知识卡':'展开知识卡'" @click="cardVisible=!cardVisible"><PanelRightClose v-if="cardVisible" :size="17"/><PanelRightOpen v-else :size="17"/></button></div></div>
    <div class="scene-area" :class="{compact:s.mode!=='universe'&&s.mode!=='directory'&&s.mode!=='resources'}" v-show="!['resources','directory'].includes(s.mode)">
     <div class="scene-metrics"><span><b>{{displayCount}}</b> 知识节点</span><i></i><span><b>6</b> 知识星系</span><i></i><span><b>5</b> 认知层级</span></div>
     <UniverseScene/>
     <div class="scene-hint">拖动旋转 · 滚轮缩放 · 点击节点聚焦</div>
     <div class="scene-quality"><select aria-label="渲染质量" v-model="s.quality"><option value="balanced">均衡画质</option><option value="low">低功耗</option></select></div>
    </div>
    <div v-if="s.mode==='universe'" class="universe-bottom"><div class="level-heading"><span class="eyebrow">COGNITIVE ALTITUDE</span><span>按认知层级探索</span><button @click="s.levelFilter=0" :class="{active:!s.levelFilter}">全部层级</button></div><div class="level-rail"><button v-for="(name,i) in levels" :key="name" :class="{active:s.levelFilter===i+1}" @click="s.levelFilter=s.levelFilter===i+1?0:i+1"><span>0{{i+1}}</span><b>{{name}}</b><small>{{s.nodes.filter(n=>n.level===i+1).length}} 个节点</small></button></div><div class="legend-row"><span v-for="(color,type) in typeColors" :key="type"><i :style="{background:color}"></i>{{typeNames[type]}}</span><select aria-label="关系筛选" v-model="s.relationFilter"><option value="all">全部关系</option><option v-for="(label,type) in relationNames" :key="type" :value="type">{{label}}</option></select></div></div>
    <section v-if="s.mode==='path'" class="mode-panel path-panel"><div class="panel-toolbar"><label>学习目标<select v-model="s.pathTarget" @change="s.focus(s.pathTarget)"><option v-for="n in s.nodes" :key="n.id" :value="n.id">{{n.name}}</option></select></label><label>方向<select v-model="s.pathDirection"><option value="before">回溯所有先修</option><option value="after">探索后续知识</option></select></label><button class="primary" @click="toggleTour"><Pause v-if="tourTimer" :size="15"/><Play v-else :size="15"/>{{tourTimer?'暂停漫游':'沿路径漫游'}}</button><button @click="exportPath" aria-label="导出学习路径"><Download :size="16"/></button></div><div class="path-summary"><b>{{s.path.length}} 个学习单元</b><span>先修关系自动计算 · 包含分支 · 可点击任意一步</span></div><div class="path-steps"><button v-for="(id,i) in s.path" :key="id" :class="{active:s.selectedId===id,current:s.tourIndex===i}" @click="stopTour();s.focus(id)"><span>{{String(i+1).padStart(2,'0')}}</span><b>{{s.byId[id].name}}</b><small>L{{s.byId[id].level}} · {{s.byId[id].chapter}}</small><ChevronRight :size="14"/></button></div></section>
    <section v-if="s.mode==='compare'" class="mode-panel comparison-panel"><div class="panel-toolbar"><label>课程方法对照<select v-model="s.comparisonId"><option v-for="c in s.comparisons" :key="c.id" :value="c.id">{{c.title}}</option></select></label><span class="muted">6 组课程对照</span></div><div class="common-foundations"><span>共同先修</span><button v-for="id in s.context.common" :key="id" @click="s.focus(id)">{{s.byId[id].name}}</button><span v-if="!s.context.common.length">当前先修图未记录共同前置。</span></div><table><thead><tr><th>比较维度</th><th v-for="id in s.comparison.method_ids" :key="id"><button @click="s.focus(id)">{{s.byId[id].name}} ↗</button></th></tr></thead><tbody><tr v-for="row in s.comparison.rows" :key="row.dimension"><th>{{row.dimension}}</th><td v-for="(value,i) in row.values" :key="i">{{value}}</td></tr></tbody></table><p class="takeaway">{{s.comparison.takeaway}}</p><button class="text-button" @click="s.openResource(s.comparison.sources[0].resource_id,s.comparison.sources[0])">核对比较依据 <ArrowUpRight :size="13"/></button></section>
    <section v-if="s.mode==='problems'" class="mode-panel"><div class="problem-selector"><button v-for="(p,i) in s.problems" :key="p.id" :class="{active:s.problemId===p.id}" @click="s.problemId=p.id"><span>0{{i+1}}</span>{{p.title}}</button></div><div class="recommendation"><span class="eyebrow">从问题到方法</span><h2>{{s.problem.title}}</h2><p>{{s.problem.condition}}</p><div class="recommendation-methods"><button v-for="id in s.problem.method_ids" :key="id" @click="s.focus(id)">{{s.byId[id].name}}<ArrowUpRight :size="16"/></button></div><p class="notice">{{s.problem.warning}}</p><button class="text-button" @click="s.makePath(s.problem.method_ids[0])">为此方法生成学习路径 <ArrowRight :size="14"/></button></div></section>
    <section v-if="s.mode==='cases'" class="mode-panel"><div class="panel-toolbar"><label>任务领域<select aria-label="案例领域" v-model="caseDomain"><option value="all">全部领域</option><option v-for="d in [...new Set(s.cases.map(c=>c.domain))]" :key="d">{{d}}</option></select></label><span class="muted">{{caseList.length}} 个原课程案例 · 案例地图按任务组织</span></div><div class="case-grid"><button v-for="(c,i) in caseList" :key="c.id" :class="{active:s.caseId===c.id}" @click="s.caseId=c.id"><small>{{c.domain}} <ArrowUpRight :size="14"/></small><h3>{{c.title}}</h3><span>{{c.data.sheet}} · {{c.method_ids.map(id=>s.byId[id].name).join(' / ')}}</span></button></div><article class="case-detail"><div><span class="tag">{{s.caseItem.status}}</span><h2>{{s.caseItem.title}}</h2><p>{{s.caseItem.description}}</p></div><div class="case-flow"><span>实际问题</span><ArrowRight :size="13"/><button v-for="id in s.caseItem.method_ids" :key="id" @click="s.focus(id)">{{s.byId[id].name}}</button><ArrowRight :size="13"/><span>{{s.caseItem.data.sheet}}</span></div><p><b>课堂任务：</b>{{s.caseItem.task}}</p><p><b>数据核对：</b>{{s.caseItem.data.rows}} 行 × {{s.caseItem.data.columns}} 列（工作表含表头，不等于有效样本量）。</p><div class="chips"><span v-for="h in s.caseItem.data.header" :key="h">{{h||'未命名列'}}</span></div><div class="case-actions"><button class="primary" @click="s.makePath(s.caseItem.node_id)"><Route :size="14"/>学习此案例</button><button v-for="id in s.caseItem.resource_ids" :key="id" @click="s.openResource(id,s.caseItem.sources.find(x=>x.resource_id===id))">{{id.startsWith('nb')?'Python 单元':id.startsWith('ppt')?'案例课件':'数据工作簿'}}<ArrowUpRight :size="13"/></button></div></article></section>
    <section v-if="s.mode==='resources'" class="mode-panel full-panel"><div class="panel-toolbar"><h2>课程资源库 <span class="muted">{{s.resources.length}}</span></h2><input aria-label="搜索课程资源" placeholder="搜索课件、讲义、教材…" v-model="resourceQuery"></div><p class="notice">按原始材料定位；代码查看不代表已经运行，扫描教材不视为全文已核验。</p><div class="resource-grid"><button v-for="r in resourceList" :key="r.id" @click="s.openResource(r.id)"><span class="resource-kind">{{{ppt:'PPT',lecture:'讲义',python:'PYTHON',book:'教材',dataset:'DATA'}[r.kind]}}</span><h3>{{r.title}}</h3><small>{{r.kind==='book'?'本地阅读 · 未打包全文':r.kind==='python'?'源代码可读 · 未执行':'支持来源定位'}}</small><ArrowUpRight :size="16"/></button></div><p v-if="!resourceList.length" class="empty">没有匹配资源。</p></section>
    <section v-if="s.mode==='directory'" class="mode-panel full-panel"><div class="panel-toolbar"><h2>可访问的知识目录</h2><input aria-label="筛选知识目录" placeholder="按名称或英文缩写筛选" v-model="directoryQuery"></div><p class="muted">键盘可直接访问全部节点；无 WebGL 的设备也可使用知识卡和课程资源。</p><div class="directory-list"><button v-for="n in directory" :key="n.id" @click="s.focus(n.id)"><span :style="{background:typeColors[n.type]}" class="tiny-dot"></span><strong>{{n.name}}</strong><small>{{n.chapter}} · L{{n.level}} {{levels[n.level-1]}}</small><ArrowUpRight :size="14"/></button></div><p v-if="!directory.length" class="empty">此筛选下没有知识节点。</p></section>
    <footer class="stage-footer"><span>《多元统计分析》数字课程 · 三维知识空间</span><span>基于真实课程资料构建</span></footer>
   </main>
   <KnowledgeCard v-if="cardVisible"/>
  </div>
  <ResourceViewer/>
 </div>
</template>
